# Generated by Django 2.0 on 2017-12-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watson_api', '0002_auto_20171222_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturemodel',
            name='image',
            field=models.ImageField(upload_to='pic_folder/'),
        ),
    ]
