# Generated by Django 2.0 on 2017-12-22 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watson_api', '0003_auto_20171222_0413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picturemodel',
            old_name='image',
            new_name='model_image',
        ),
    ]
